<?php
/**
 * @category    Abserve
 * @package     Abserve_Module
 * @author      Abserve Developer
 * @license     http://abservetech.com/license-agreement/
 * @copyright   Copyright (c) 2015 abservetech (http://abservetech.com)
 */
?>
<script type="text/javascript">
//<![CDATA[
<?php $menuContent = Mage::helper('custommenu')->getMenuContent(); ?>
if ($('custommenu') != undefined) {
    $('custommenu').update(<?php echo Mage::helper('core')->jsonEncode($menuContent['topMenu']); ?>);
}
abservePopupMenuContent = <?php echo Mage::helper('core')->jsonEncode($menuContent['popupMenu']); ?>;
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
<?php $mobileMenuContent = Mage::helper('custommenu')->getMobileMenuContent(); ?>
abserveMobileMenuContent = <?php echo Mage::helper('core')->jsonEncode($mobileMenuContent); ?>;
abserveCustomMenuMobileToggle();
Event.observe(window, 'resize', function() {
    abserveCustomMenuMobileToggle();
});
//]]>
</script>
