<div class="advertise_container clearfix">
	<div class="advertisement advertisement_block1">
		<a href="javascript:void(0)">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/ad_1.jpg" alt="ad">
		</a>
	</div>
	<div class="advertisement advertisement_block2">
		<a href="javascript:void(0)">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/ad_2.jpg" alt="ad">
		</a>
		<a href="javascript:void(0)">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/ad_2.jpg" alt="ad">
		</a>
	</div>
	<div class="advertisement advertisement_block3">
		<a href="javascript:void(0)">
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/ad_1.jpg" alt="ad">
		</a>
	</div>
</div>