<div class="banner_slider">
	<div id="owl-demo" class="owl-carousel owl-theme">     
  		<div class="item">
  			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/banner-2.jpg" alt="banner">
  		</div>
  		<div class="item">
  			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/banner.jpg" alt="banner">
  		</div>
  		<div class="item">
  			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/banner-2.jpg" alt="banner">
  		</div>
	</div>
</div>