<div class="blog_container clearfix">
	<div class="title"> 
	    <h2> From Our Blog </h2>
	    <p>
	        Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's tandard dummy text ever since the 1500s.
	    </p>
	</div>
	<div class="blog">
		<div class="blog_left">
			<i class="fa fa-pencil"></i>
			<h5>Posted 15May 2015</h5>
			<h6>Lorem Ipsum is simply dummy<br>text of the printing and type<br>setting industry Lorem Ipsum </h6>
		</div>
		<div class="blog_right">
			<i class="fa fa-pencil"></i>
			<h5>Posted 15May 2015</h5>
			<h6>Lorem Ipsum is simply dummy<br>text of the printing and type<br>setting industry Lorem Ipsum </h6>
		</div>
	</div>
	<div class="blog_row2">
		<div class="blog_left">
			<i class="fa fa-pencil"></i>
			<h5>Posted 15May 2015</h5>
			<h6>Lorem Ipsum is simply dummy<br>text of the printing and type<br>setting industry Lorem Ipsum </h6>
		</div>
		<div class="blog_right">
			<i class="fa fa-pencil"></i>
			<h5>Posted 15May 2015</h5>
			<h6>Lorem Ipsum is simply dummy<br>text of the printing and type<br>setting industry Lorem Ipsum </h6>
		</div>
	</div>

</div>