<div class="service_container clearfix">
	<div class="services animated slideInLeft" style="animation-delay: 5s; animation-duration:5s;">
		<i class="fa fa-tags"></i>			
	<!-- <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/service_1.png" alt="services"> -->
		<h4>Member Discount</h4>
		<h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's tandard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to </h6>
		<div class="services_link">
			<a href="">Read More</a>
		</div>
	</div>

	<div class="services animated zoomIn" style="animation-delay: 5s; animation-duration:5s;">
		<i class="fa fa-truck"></i>	
		<!-- <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/service_2.png" alt="services"> -->
		<h4>Free Delivery</h4>
		<h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's tandard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to </h6>
		<div class="services_link">
			<a href="">Read More</a>
		</div>	
	</div>

	<div class="services animated slideInLeft" style="animation-delay: 5s; animation-duration:5s;">
		<i class="fa fa-thumbs-up"></i>
		<!-- <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>settings/service_3.png" alt="services"> -->
		<h4>Free Support</h4>
		<h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's tandard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to </h6>
		<div class="services_link">
			<a href="">Read More</a>
		</div>
	</div>

</div>