<?php
    $todayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
    $_productCollection = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*');
    $_productCollection->addStoreFilter(); 
    $_productCollection->addAttributeToFilter('news_to_date', array('or'=> array(
            0 => array('date' => true, 'from' => $todayDate),
            1 => array('is' => new Zend_Db_Expr('null')))
         ), 'left');
    $_productCollection->addAttributeToSort('news_from_date', 'desc');
    $_productCollection->getSelect()->order('rand()');
    $_productCollection->setPageSize(12);
    $_helper = $this->helper('catalog/output');
    $count = $_productCollection->count();
    $_columnCount = '';
    $today = time();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="new-products clearfix">
<div class="title"> 
    <h2> New Products </h2>
    <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's tandard dummy text ever since the 1500s.
    </p>
</div>
<div class="product-carousel">
    <div class="customNavigation">
        <a class="btn prev hvr-bounce-in"> <i class="fa fa-angle-left"></i> </a> 
        <a class="btn next hvr-bounce-in"> <i class="fa fa-angle-right"></i></a>
    </div>
    <div class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">    
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php  
            $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
            $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
            $savingsDollarValue = ($_product->getPrice() - $_product->getFinalPrice());
            $originalPrice = $_product->getPrice(); 
            $discountPrice = $_product->getFinalPrice();
            $savings = $originalPrice - $discountPrice; 
            $savingsPercentage = round(($savings / $originalPrice) * 100, 0);
        ?>
        <div class="item" style="overflow:hidden">
            <?php if($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)){ ?> 
                <?php if($savingsPercentage > 0){ ?> 
                <div class="offer_price"> 
                    <?php echo $this->getIdSuffix() ?> <?php echo $savingsPercentage, '%'; ?> 
                    <br/> 
                    Offer 
                </div>
                <?php } ?>
            <?php } ?>           

            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 300; ?>
                <img class="lazyOwl" id="product-collection-image-<?php echo $_product->getId(); ?>"
                     data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif');?> "
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" onmouseover="this.src='<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300) ?>';" onmouseout="this.src='<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300) ?>';" />
            </a>

            <div class="product-info">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php
                if ($this->getChild('name.after')) {
                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                        $_nameAfterChild->setProduct($_product);
                        echo $_nameAfterChild->toHtml();
                    }
                }
                ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                
                <div class="actions">
                    <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>?options=cart')"><i class="fa fa-shopping-cart"></i><span><span><?php echo $this->__('Add to cart') ?></span></span></button>
                    <?php elseif($_product->isSaleable()): ?>
                        <a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><i class="fa fa-eye"></i><?php echo $this->__('View Details') ?></a>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links clearfix">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><i class="fa fa-heart"></i><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"  onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><i class="fa fa-files-o"></i><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>                
                </div>
                
            </div>
            </div>
            <?php endforeach ?>
        </div>
    </div>
</div>
<?php endif; ?>