<?php
/**
 * @category    Abserve
 * @package     Abserve_Module
 * @author      Abserve Developer
 * @license     http://abservetech.com/license-agreement/
 * @copyright   Copyright (c) 2015 abservetech (http://abservetech.com)
 */
?>
<?php if ($this->getTotals()): ?>
<tfoot>
	<tr><td colspan="2">&nbsp;</td><td>&nbsp;</td></tr>
    <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 3 : 2; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr>        
        <td class="a-right" colspan="<?php echo $_colspan; ?>">
            <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
        </td>
        <td class="a-right">
            <small><?php echo $this->displayBaseGrandtotal() ?></small>
        </td>
    </tr>
    <?php endif?>
	<tr><td colspan="2">&nbsp;</td><td>&nbsp;</td></tr>
</tfoot>
<?php endif; ?>
