<?php
/**
 * @category    Abserve
 * @package     Abserve_Module
 * @author      Abserve Developer
 * @license     http://abservetech.com/license-agreement/
 * @copyright   Copyright (c) 2015 abservetech (http://abservetech.com)
 */
?>
<?php $_helper = Mage::helper('onestepcheckout');?>
<?php if ($_helper->enabledOnestepcheckout()):?>
	<button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-checkout" onclick="window.location='<?php echo $_helper->getCheckoutUrl(); ?>';"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
<?php else:?>
	<?php if ($this->isPossibleOnepageCheckout()):?>
	  <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
	<?php endif?>
<?php endif;?>